### ISSUE TITLE
Analysis: Image Scaling when converting ECAT to nii w/ python

### ISSUE THREAD

**Issue by bendhouseart** [openneuropet/BIDS-converter#11]
Presently scaling of the nifti image is performed in the same way as the Matlab converters, that is to say a single scaling factor is applied to the entire 4d image matrix. 

However it might be more desirable to use the sub-header scaling factor on a per frame basis if the scaling factor is unique for each frame. This code block already exists in the python version of the converter, but it need to be tested and evaluated in comparison to whole matrix scaling. 

```python
calibration_factor = subheader['SCALE_FACTOR'] * main_header['ECAT_CALIBRATION_FACTOR']
calibrated_pixel_data_matrix_3d = calibration_factor * pixel_data_matrix_3d
data.append(calibrated_pixel_data_matrix_3d)
```

**Comment by bendhouseart** [comment]
@CPernet I created this, but is it the same issue as the scaling by subheader? I probably shouldn't be reading these until I've finished my coffee.

**Comment by CPernet** [comment]
nope - there is the frame wise calibration factor but the one in your json the DoseCalibrationFactor is something people enter in the machine one in a while by doing the  external calibration to a know radioactive source = ecat_calibration_factor here https://github.com/openneuropet/BIDS-converter/blob/main/code/matlab/ecat2nii.m#L218 (rescaled)

**Comment by bendhouseart** [comment]
Ah alright, then I think we can close this issue as it's been handled.
