### ISSUE TITLE
Sidecar field Description not specific

### ISSUE THREAD

**Issue by neurolabusc** [openneuropet/BIDS-converter#25]
I suggest changing the sidecar field from  [`Description`](https://github.com/openneuropet/BIDS-converter/blob/5d4a6094a83c785356d6353c1ac19ece1b1357c9/matlab/ecat2nii.m#L226) to `ConversionSoftware`.  This makes the purpose of the tag more specific and matches the usage of dcm2niix and dicm2nii.  You may want to also report the version of the converter, for example dcm2niix generates a field `ConversionSoftwareVersion`, e.g.

```
	"ConversionSoftware": "dcm2niix",
	"ConversionSoftwareVersion": "v1.0.20210819"
```

**Comment by CPernet** [comment]
at the moment for ecat we use our own converter - but when writing one calling dcm2nixx of course we will!

**Comment by neurolabusc** [comment]
I think it is great to develop independent converters. My comment was that your converter should identify itself with the JSON attribute `ConversionSoftware` rather than `Description`. This attribute is not defined in BIDS, but it is a convention used by other converters. Using the same attribute names across converters makes it easier for scripts to consistently identify the tool used. Beyond that, I do not think the attribute `Description` is very specific to what the attribute means, where the the attribute `ConversionSoftware` is very explicit.

**Comment by CPernet** [comment]
@bendhouseart let's do this! thx Chris
